[project]
name = "oaiteamcrsregister"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "drissionpage>=4.1.1.2",
    "requests>=2.32.5",
    "setuptools>=80.9.0",
    "tomli>=2.3.0",
]
